using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace Tm7.Cli.Model;

[DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ThreatModeling.Common")]
public enum AttributeType
{
    [EnumMember] List
}

[DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ThreatModeling.Common")]
public enum AttributeInheritance
{
    [EnumMember] Virtual,
    [EnumMember] New
}

[DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ThreatModeling.Common")]
public enum AttributeMode
{
    [EnumMember] Static,
    [EnumMember] Dynamic
}

[DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ThreatModeling.Common")]
public enum ThreatState
{
    [EnumMember] AutoGenerated = 0,
    [EnumMember] NotApplicable = 1,
    [EnumMember] NeedsInvestigation = 2,
    [EnumMember] Mitigated = 3,
    [EnumMember] NeedsMitigation = NeedsInvestigation,
    [EnumMember] Migrated = AutoGenerated
}

[DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ThreatModeling.Common")]
public enum StencilConnectionPort
{
    [EnumMember] None,
    [EnumMember] North,
    [EnumMember] NorthEast,
    [EnumMember] East,
    [EnumMember] SouthEast,
    [EnumMember] South,
    [EnumMember] SouthWest,
    [EnumMember] West,
    [EnumMember] NorthWest
}

[Serializable]
[DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ThreatModeling.Common")]
public enum ElementVisualRepresentation
{
    [EnumMember] [XmlEnum("None")] None,
    [EnumMember] [XmlEnum("Ellipse")] Ellipse,
    [EnumMember] [XmlEnum("ParallelLines")] ParallelLines,
    [EnumMember] [XmlEnum("Rectangle")] Rectangle,
    [EnumMember] [XmlEnum("Line")] Line,
    [EnumMember] [XmlEnum("LineBoundary")] LineBoundary,
    [EnumMember] [XmlEnum("BorderBoundary")] BorderBoundary,
    [EnumMember] [XmlEnum("Inherited")] Inherited,
    [EnumMember] [XmlEnum("Annotation")] Annotation,
    [EnumMember] [XmlEnum("UndefinedBoundary")] UndefinedBoundary,
    [EnumMember] [XmlEnum("UndefinedTarget")] UndefinedTarget
}
